baseURL = "https://carsonhe.dev/"
languageCode = "en-us"
title = "Carson He"

enableRobotsTXT = true

# https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches.images]
dir = ':cacheDir/images'

# https://gohugo.io/content-management/markdown-attributes/
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[params]
math = true

[markup.highlight]
noClasses = false
